server:
  port: 9999

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql
#    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
    # pgsql
    url: jdbc:postgresql://47.93.145.101:5432/code_manage
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: false
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123

# mybatis-plus
#    # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/repository/*Mapper.xml
#    # 如果是放在resource目录 classpath:/repository/*Mapper.xml
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  global-config:
    db-config:
      #主键类型，AUTO:"数据库ID自增", INPUT:"用户输入ID",id_worker:"全局唯一ID (数字类型唯一ID)", uuid:"全局唯一ID UUID";
      id-type: assign_uuid
      #逻辑未删除值（默认为0）
      logic-not-delete-value: 0
      #逻辑已删除值（默认为1）
      logic-delete-field: 1
      #字段更新策略 ignored:"忽略判断",not_null:"非 NULL 判断"),not_empty:"非空判断"
      update-strategy: not_null
  configuration:
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志配置
logging:
  config: classpath:logback-line.xml
  level:
    com:
      baomidou:
        mybatisplus: DEBUG